config/routes.rb
Rails.application.routes.draw do
  resources :invoice_data_items
  resources :invoices
  resources :batches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'batches#index'
  
end

app/models/invoice_data_item.rb
# Модель для объекта InvoiceDataItem (Товар, указанный в инфойсе)
class InvoiceDataItem < ApplicationRecord
  belongs_to :invoice
end

app/controllers/invoice_data_items_controller.rb
class InvoiceDataItemsController < ApplicationController
  before_action :set_invoice_data_item, only: [:show, :edit, :update, :destroy]

  # GET /invoice_data_items
  # GET /invoice_data_items.json
  def index
    @invoice_data_items = InvoiceDataItem.all
  end

  # GET /invoice_data_items/1
  # GET /invoice_data_items/1.json
  def show
  end

  # GET /invoice_data_items/new
  def new
    @invoice_data_item = InvoiceDataItem.new
  end

  # GET /invoice_data_items/1/edit
  def edit
  end

  # POST /invoice_data_items
  # POST /invoice_data_items.json
  def create
    @invoice_data_item = InvoiceDataItem.new(invoice_data_item_params)

    respond_to do |format|
      if @invoice_data_item.save
        format.html { redirect_to @invoice_data_item, notice: 'Invoice data item was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_data_item }
      else
        format.html { render :new }
        format.json { render json: @invoice_data_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_data_items/1
  # PATCH/PUT /invoice_data_items/1.json
  def update
    respond_to do |format|
      if @invoice_data_item.update(invoice_data_item_params)
        format.html { redirect_to @invoice_data_item, notice: 'Invoice data item was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_data_item }
      else
        format.html { render :edit }
        format.json { render json: @invoice_data_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_data_items/1
  # DELETE /invoice_data_items/1.json
  def destroy
    @invoice_data_item.destroy
    respond_to do |format|
      format.html { redirect_to invoice_data_items_url, notice: 'Invoice data item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_data_item
      @invoice_data_item = InvoiceDataItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_data_item_params
      params.require(:invoice_data_item).permit(:parcel_code, :item_qty, :parcel_price, :invoice_id)
    end
end

app/helpers/invoice_data_items_helper.rb
module InvoiceDataItemsHelper
end

app/views/invoice_data_items/_form.html.erb
<!-- Стандартная форма объекта Инвойс -->
<%= form_with(model: invoice_data_item, local: true) do |form| %>
  <% if invoice_data_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice_data_item.errors.count, "error") %> prohibited this invoice_data_item from being saved:</h2>

      <ul>
        <% invoice_data_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :parcel_code %>
    <%= form.number_field :parcel_code %>
  </div>

  <div class="field">
    <%= form.label :item_qty %>
    <%= form.number_field :item_qty %>
  </div>

  <div class="field">
    <%= form.label :parcel_price %>
    <%= form.number_field :parcel_price %>
  </div>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.text_field :invoice_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_data_items/edit.html.erb
<!-- Форма редактирования объекта Инвойс -->
<h1>Editing Invoice Data Item</h1>

<%= render 'form', invoice_data_item: @invoice_data_item %>

<%= link_to 'Show', @invoice_data_item %> |
<%= link_to 'Back', invoice_data_items_path %>

app/views/invoice_data_items/index.html.erb
<!-- Список всех инвойсов -->
<p id="notice"><%= notice %></p>

<h1>Invoice Data Items</h1>

<table>
  <thead>
    <tr>
      <th>Parcel code</th>
      <th>Item qty</th>
      <th>Parcel price</th>
      <th>Invoice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_data_items.each do |invoice_data_item| %>
      <tr>
        <td><%= invoice_data_item.parcel_code %></td>
        <td><%= invoice_data_item.item_qty %></td>
        <td><%= invoice_data_item.parcel_price %></td>
        <td><%= invoice_data_item.invoice_id %></td>
        <td><%= link_to 'Show', invoice_data_item %></td>
        <td><%= link_to 'Edit', edit_invoice_data_item_path(invoice_data_item) %></td>
        <td><%= link_to 'Destroy', invoice_data_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice Data Item', new_invoice_data_item_path %>

app/views/invoice_data_items/new.html.erb
<!-- Форма создания нового инвойса -->
<h1>New Invoice Data Item</h1>

<%= render 'form', invoice_data_item: @invoice_data_item %>

<%= link_to 'Back', invoice_data_items_path %>

app/views/invoice_data_items/show.html.erb
<!-- Форма для показа данных инвойса -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Parcel code:</strong>
  <%= @invoice_data_item.parcel_code %>
</p>

<p>
  <strong>Item qty:</strong>
  <%= @invoice_data_item.item_qty %>
</p>

<p>
  <strong>Parcel price:</strong>
  <%= @invoice_data_item.parcel_price %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @invoice_data_item.invoice_id %>
</p>

<%= link_to 'Edit', edit_invoice_data_item_path(@invoice_data_item) %> |
<%= link_to 'Back', invoice_data_items_path %>