config/routes.rb
Rails.application.routes.draw do
  resources :invoice_data_items
  resources :invoices
  resources :batches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'batches#index'
  
end

app/models/invoice.rb
# Модель для объекта Инвойс
class Invoice < ApplicationRecord
  belongs_to :batch
  has_many :invoice_data_items
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:invoice_operation_number, :invoice_operation_date, :company_code, :batch_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<!-- Стандартная форма объекта "Товар из инвойса" -->
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :invoice_operation_number %>
    <%= form.number_field :invoice_operation_number %>
  </div>

  <div class="field">
    <%= form.label :invoice_operation_date %>
    <%= form.date_select :invoice_operation_date %>
  </div>

  <div class="field">
    <%= form.label :company_code %>
    <%= form.text_field :company_code %>
  </div>

  <div class="field">
    <%= form.label :batch_id %>
    <%= form.text_field :batch_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<!-- Форма редактирования объекта "Товар из инвойса" -->
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<!-- Список всех товаров из инвойса -->
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Invoice operation number</th>
      <th>Invoice operation date</th>
      <th>Company code</th>
      <th>Batch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_operation_number %></td>
        <td><%= invoice.invoice_operation_date %></td>
        <td><%= invoice.company_code %></td>
        <td><%= invoice.batch_id %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<!-- Форма создания нового товара из инвойса -->
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<!-- Форма для показа данных товаров из инвойса -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice operation number:</strong>
  <%= @invoice.invoice_operation_number %>
</p>

<p>
  <strong>Invoice operation date:</strong>
  <%= @invoice.invoice_operation_date %>
</p>

<p>
  <strong>Company code:</strong>
  <%= @invoice.company_code %>
</p>

<p>
  <strong>Batch:</strong>
  <%= @invoice.batch_id %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>