config/routes.rb
Rails.application.routes.draw do
  resources :invoice_data_items
  resources :invoices
  resources :batches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'batches#index'
  
end

app/models/batch.rb
# Модель для объекта Batch (загрузка файла)
class Batch < ActiveRecord::Base
    has_many :invoices
    # Метод, возвращающий ID загруженного файла по GUID (проверяет наличие файла с данным GUID в БД)
    def self.find_batch_by_guid(guid)
        batch = Batch.select("batch_id").where(:guid => guid).first
        return batch
    end
end

app/controllers/batches_controller.rb
require "rexml/document"
include REXML

class BatchesController < ApplicationController
  # Инициализация данных объекта Batch
  before_action :set_batch, only: [:show, :edit, :update, :destroy]

  # GET /batches
  # GET /batches.json
  def index
    # Получаем список всех загруженных файлов
    @batches = Batch.all
  end

  # GET /batches/1
  # GET /batches/1.json
  def show
    # Используем умолчания Rails. Показываем стандартные поля объекта Batch
  end

  # GET /batches/new
  def new
    # Инициализируем новый объект Batch
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
    # Используем умолчания Rails для редактирования полей объекта Batch
  end

  # POST /batches
  # POST /batches.json
  def create
    # Сохраняем данные из загруженного файла
    # Инициализируем объект Batch с параметрами
    @batch = Batch.new(batch_params)
    # Загруженный файл
    uploaded_io = params[:batch][:batch_file]
    @file_path = "/public/uploads/#{uploaded_io.original_filename}"
    @xml_file = File.new(Rails.root.join('public', 'uploads', uploaded_io.original_filename))
    # Создаем новый документ XML. Выбираем интересующие нас элементы по имени/шаблону
    @xml_doc = Document.new(@xml_file)
    @root = @xml_doc.root
    @file_attribute_guid = @root.elements["FileAttribute/GUID"]
    # Берем содержимое ноды
    @batch.guid = @file_attribute_guid.text

    # Ищем загруженный файл в базе по GUID
    @existing_batch = Batch.find_batch_by_guid(@batch.guid)

    if @existing_batch != nil
      # Если файл существует, не сохраняем его данные
      @guid_error = "Batch file with GUID provided already exists in database"
    else
      # Файл не найден в базе, обрабатываем его данные
      @batch_id_data = @root.elements["FileData/Batch/BatchID"]
      @batch.batch_id = @batch_id_data.text
      @batch_creation_date_data = @root.elements["FileData/Batch/CreationDate"]
      @batch.creation_date = @batch_creation_date_data.text
      @batch.batch_file = @file_path
      # Сохраняем данные загруженного файла в базу
      @batch.save

      # Для каждой ноды "Invoice" внутри "FileData" сохраняем её данные в соответствующую таблицу БД
      @root.elements.each("FileData/Invoice") do |invoice|
        @invoice = @batch.invoices.create(
          invoice_operation_number: invoice.elements["InvoiceOperation/InvoiceOperationNumber"].text,
          invoice_operation_date: invoice.elements["InvoiceOperation/InvoiceOperationDate"].text,
          company_code: invoice.elements["InvoiceOperation/CompanyCode"].text,
          )
        # Сохраняем Инвойс
        @invoice.save
        # Теперь повторяем то же самое для каждого товара в инвойсе
        # Выбираем ноды "InvoiceData" внутрни инвойса и сохраняем их данные в таблицу invoice_data_items
        invoice.elements.each("InvoiceData") do |invoice_data_item|
          @invoice_data_item = @invoice.invoice_data_items.create(
            parcel_code: invoice_data_item.elements["ParcelCode"].text,
            item_qty: invoice_data_item.elements["ItemQty"].text,
            parcel_price: invoice_data_item.elements["ParcelPrice"].text,
            )
          # Сохраняем данные в БД
          @invoice_data_item.save
        end
      end
    end

    respond_to do |format|
      if @existing_batch != nil
        # Если файл с данным GUID уже существует в базе, возвращаемся к списку загрузок и выводим соответствующее предупреждение
        format.html { redirect_to batches_url, alert: @guid_error }
        format.json { head :no_content }
      else
        # Если сохранение объекта Batch прошло удачно, переходим на страницу показа и показываем соответствующее сообщение
        if @batch.save
          format.html { redirect_to @batch, notice: 'Batch was successfully uploaded.' }
          format.json { render :show, status: :created, location: @batch }
        else
          # В противном случае, остаемся на странице загрузки данных и показываем сообщение об ошибке
          format.html { render :new }
          format.json { render json: @batch.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /batches/1
  # PATCH/PUT /batches/1.json
  def update
    # При редактировании объекта Batch, используем уиолчания Rails
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to @batch, notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    # При удалении объекта Batch из БД, используем уиолчания Rails
    @batch.destroy
    respond_to do |format|
      format.html { redirect_to batches_url, notice: 'Batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      # Находим данные объекта Batch по id
      @batch = Batch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batch_params
      # Инициализация параметров объекта Batch
      params.require(:batch).permit(:batch_id, :creation_date, :guid, :batch_file)
    end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.erb
<!-- Стандартная форма объекта Batch -->
<%= form_with(model: batch, local: true) do |form| %>
  <% if batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
        <% batch.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :batch_id %>
    <%= form.number_field :batch_id %>
  </div>

  <div class="field">
    <%= form.label :creation_date %>
    <%= form.date_select :creation_date %>
  </div>

  <div class="field">
    <%= form.label :guid %>
    <%= form.text_field :guid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<!-- Форма редактирования объекта Batch -->
<h1>Editing Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<!-- Главная страница (список всех загрузок) -->
<% if !flash[:alert].blank? %>
  <div class = "alert">
    <%= flash[:alert] %>
  </div>
<% end %>

<% if !flash[:notice].blank? %>
  <div class = "alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<!--p id="notice"--><!--%= notice %--><!--/p-->

<h1>Batches</h1>

<table>
  <thead>
    <tr>
      <th>Batch</th>
      <th>Creation date</th>
      <th>Guid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.batch_id %></td>
        <td><%= batch.creation_date %></td>
        <td><%= batch.guid %></td>
        <td><%= link_to 'Show', batch %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
        <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Upload Batch File", new_batch_path, class: "btn btn-primary" %>
<br />
<br />

app/views/batches/new.html.erb
<!-- Форма загрузки нового файла с данными -->
<h1>Upload New Batch File</h1>

<% if !@batch.errors.empty? %>
  <div class = "alert alert-error">

    <ul>
      <% @batch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<div class = "well">
  <%= form_for @batch, html: { multipart: true } do |f| %>
    <%= f.label :attachment %>
    <%= f.file_field :batch_file %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<!-- Страница показа данных из загруженного файла -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Batch:</strong>
  <%= @batch.batch_id %>
</p>

<p>
  <strong>Creation date:</strong>
  <%= @batch.creation_date %>
</p>

<p>
  <strong>Guid:</strong>
  <%= @batch.guid %>
</p>

<p>
  <strong>Attachment:</strong>
  <% if @batch.batch_file %>
    <br /><%= @batch.batch_file %></br>
  <% end %>
</p>

<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>